//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tarea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zologico
    {
        public int id { get; set; }
        public string pais { get; set; }
        public string nombre { get; set; }
        public Nullable<int> telefono { get; set; }
        public string sitioWeb { get; set; }
    }
}
